//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.10.03 at 02:07:26 PM PKT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.tibco.com/schemas/MEF/SharedResources/Schemas/SecureAdapters/NotifyMe/Schema.xsd2", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package wsdl.remove.business.service;
